"""add lead, atividade_prospeccao, metrica_diaria

Revision ID: 884ce8c94979
Revises: 
Create Date: 2026-09-16 01:37:02.010973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '884ce8c94979'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('empresa', sa.String(length=200), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('papel_decisor', sa.Enum('decisor', 'influenciador', 'usuario', name='papel_decisor_enum'), nullable=True),
    sa.Column('pipeline_stage', sa.Enum('base_nao_verificado', 'informacao_solida', 'janela_identificada', 'conquista_prioritaria', 'indicacao_quente', 'qualificado_pronto', name='pipeline_stage_enum'), nullable=False),
    sa.Column('nivel_qualificacao', sa.Enum('nao_qualificado', 'semiqualificado', 'qualificado_sem_janela', 'qualificado_na_janela', name='nivel_qualificacao_enum'), nullable=True),
    sa.Column('nivel_familiaridade', sa.Enum('inativo', 'familiar_na_janela', 'familiar_fora_janela', 'indicacao_quente', 'pouca_familiaridade', 'frio', name='nivel_familiaridade_enum'), nullable=True),
    sa.Column('tentativas_contato', sa.Integer(), nullable=False),
    sa.Column('territorio', sa.String(length=200), nullable=True),
    sa.Column('origem', sa.String(length=200), nullable=True),
    sa.Column('vertical', sa.String(length=200), nullable=True),
    sa.Column('produto_interesse', sa.String(length=200), nullable=True),
    sa.Column('sazonal', sa.Boolean(), nullable=False),
    sa.Column('nome_guardiao', sa.String(length=200), nullable=True),
    sa.Column('relacionamento_guardiao', sa.String(length=200), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metricas_diarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ligacoes', sa.Integer(), nullable=False),
    sa.Column('contatos_efetivos', sa.Integer(), nullable=False),
    sa.Column('emails_enviados', sa.Integer(), nullable=False),
    sa.Column('respostas', sa.Integer(), nullable=False),
    sa.Column('reunioes_agendadas', sa.Integer(), nullable=False),
    sa.Column('vendas_fechadas', sa.Integer(), nullable=False),
    sa.Column('acoes_sociais', sa.Integer(), nullable=False),
    sa.Column('mensagens_texto_enviadas', sa.Integer(), nullable=False),
    sa.Column('novos_dados_coletados', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data')
    )
    op.create_table('atividades_prospeccao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.Enum('telefone', 'presencial', 'email', 'venda_social', 'mensagem_texto', 'referencia', 'networking', 'indicacao_interna', 'feira_comercial', 'chamada_fria', name='canal_enum'), nullable=False),
    sa.Column('canal_anterior', sa.Enum('telefone', 'presencial', 'email', 'venda_social', 'mensagem_texto', 'referencia', 'networking', 'indicacao_interna', 'feira_comercial', 'chamada_fria', name='canal_enum'), nullable=True),
    sa.Column('objetivo_contato', sa.Enum('marcar_reuniao', 'qualificar_informacao', 'fechar_venda', 'construir_familiaridade', name='objetivo_contato_enum'), nullable=False),
    sa.Column('resultado', sa.Enum('resposta_reflexo', 'dispensa', 'objecao', 'reuniao_marcada', 'venda_fechada', 'sem_resposta', name='resultado_contato_enum'), nullable=True),
    sa.Column('motivo_recusa', sa.Enum('sem_interesse', 'sem_orcamento', 'ocupado', 'pedido_info', 'sobrecarga', 'so_olhando', name='motivo_recusa_enum'), nullable=True),
    sa.Column('tecnica_bypass_usada', sa.Enum('outro_ramal', 'vendedor_ajuda_vendedor', 'entrada_lateral', 'ligacao_cedo_tarde', 'bilhete_escrito', name='tecnica_bypass_enum'), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atividades_prospeccao_lead_id'), 'atividades_prospeccao', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atividades_prospeccao_lead_id'), table_name='atividades_prospeccao')
    op.drop_table('atividades_prospeccao')
    op.drop_table('metricas_diarias')
    op.drop_table('leads')
    # ### end Alembic commands ###

    # Ajuste manual (nao gerado pelo autogenerate): op.drop_table() nao derruba
    # os tipos ENUM nativos do Postgres associados as colunas. Sem isso, um
    # upgrade seguinte falha com "type X already exists" (achado real durante
    # QA da story 1.2 - ver docs/stories/1.2.leads-prospeccao.story.md).
    for enum_name in (
        "papel_decisor_enum",
        "pipeline_stage_enum",
        "nivel_qualificacao_enum",
        "nivel_familiaridade_enum",
        "canal_enum",
        "objetivo_contato_enum",
        "resultado_contato_enum",
        "motivo_recusa_enum",
        "tecnica_bypass_enum",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
