"""meta_atividades em metrica_diaria

Revision ID: c1009176abea
Revises: fd9d66f4f812
Create Date: 2026-09-16 11:12:59.676465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1009176abea'
down_revision: Union[str, None] = 'fd9d66f4f812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metricas_diarias', sa.Column('meta_atividades', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('metricas_diarias', 'meta_atividades', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metricas_diarias', 'meta_atividades')
    # ### end Alembic commands ###
