"""atividade_prospeccao_lead_opcional_empresario

Revision ID: c551ea82b29d
Revises: 276ff491e875
Create Date: 2026-09-25 10:15:12.487129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c551ea82b29d'
down_revision: Union[str, None] = '276ff491e875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atividades_prospeccao', sa.Column('empresario_fonte', sa.String(length=50), nullable=True))
    op.add_column('atividades_prospeccao', sa.Column('empresario_record_id', sa.String(length=50), nullable=True))
    op.add_column('atividades_prospeccao', sa.Column('empresario_nome', sa.String(length=200), nullable=True))
    op.alter_column('atividades_prospeccao', 'lead_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('atividades_prospeccao', 'lead_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('atividades_prospeccao', 'empresario_nome')
    op.drop_column('atividades_prospeccao', 'empresario_record_id')
    op.drop_column('atividades_prospeccao', 'empresario_fonte')
    # ### end Alembic commands ###
