"""configuracao_produto

Revision ID: ebc35103d074
Revises: c1009176abea
Create Date: 2026-09-16 12:08:56.029020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc35103d074'
down_revision: Union[str, None] = 'c1009176abea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_produto', sa.String(length=200), nullable=True),
    sa.Column('proposta_valor', sa.Text(), nullable=True),
    sa.Column('dor_resolvida', sa.Text(), nullable=True),
    sa.Column('entregavel_1', sa.String(length=300), nullable=True),
    sa.Column('entregavel_2', sa.String(length=300), nullable=True),
    sa.Column('entregavel_3', sa.String(length=300), nullable=True),
    sa.Column('faixa_preco', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracao_produto')
    # ### end Alembic commands ###
