"""etapa_processo, reuniao_venda, referido

Revision ID: fd9d66f4f812
Revises: 884ce8c94979
Create Date: 2026-09-16 10:48:45.059725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'fd9d66f4f812'
down_revision: Union[str, None] = '884ce8c94979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_origem_id', sa.Integer(), nullable=False),
    sa.Column('nome_indicado', sa.String(length=200), nullable=False),
    sa.Column('contato_indicado', sa.String(length=200), nullable=False),
    sa.Column('mensagem_validacao_enviada', sa.Boolean(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_origem_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referidos_lead_origem_id'), 'referidos', ['lead_origem_id'], unique=False)
    op.create_table('reunioes_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('etapa_atual', sa.Enum('apresentacao', 'conexao', 'decisao_imediata', 'showtime', 'fechamento', 'referidos', 'validacao', name='etapa_reuniao_enum'), nullable=False),
    sa.Column('di_confirmada', sa.Boolean(), nullable=False),
    sa.Column('di_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resultado', sa.Enum('ganho', 'perdido', 'em_andamento', name='resultado_reuniao_enum'), nullable=True),
    sa.Column('valor_fechado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reunioes_venda_lead_id'), 'reunioes_venda', ['lead_id'], unique=False)

    # Ajuste manual (nao gerado pelo autogenerate): op.add_column() numa
    # tabela JA EXISTENTE nao cria o tipo ENUM sozinho (diferente de
    # create_table, que cria o tipo automaticamente como parte da propria
    # DDL). Precisa criar o tipo explicitamente antes do ADD COLUMN.
    etapa_processo_enum = postgresql.ENUM(
        'prospeccao', 'follow_prospeccao', 'qualificado', 'desqualificado',
        'assentamento', 'reuniao_venda', 'negociacao', 'fechado_ganho', 'fechado_perdido',
        name='etapa_processo_enum',
    )
    etapa_processo_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('leads', sa.Column('etapa_processo', etapa_processo_enum, nullable=False, server_default='prospeccao'))
    op.alter_column('leads', 'etapa_processo', server_default=None)
    op.add_column('leads', sa.Column('decisor_confirmado_presente', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    # Ajuste manual (nao gerado pelo autogenerate): adiciona o valor novo ao
    # enum ja existente objetivo_contato_enum, sem recriar o tipo. Seguro
    # dentro da mesma transacao porque nao lemos/filtramos por esse valor
    # aqui (Postgres 12+ permite ADD VALUE em transacao nessas condicoes).
    op.execute("ALTER TYPE objetivo_contato_enum ADD VALUE IF NOT EXISTS 'assentamento'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'decisor_confirmado_presente')
    op.drop_column('leads', 'etapa_processo')
    op.drop_index(op.f('ix_reunioes_venda_lead_id'), table_name='reunioes_venda')
    op.drop_table('reunioes_venda')
    op.drop_index(op.f('ix_referidos_lead_origem_id'), table_name='referidos')
    op.drop_table('referidos')
    # ### end Alembic commands ###

    # Ajuste manual: op.drop_column/drop_table nao derrubam os tipos ENUM
    # nativos associados (mesma pegadinha das stories 1.2/1.3). NAO
    # removemos o valor 'assentamento' de objetivo_contato_enum aqui -
    # Postgres nao tem DROP VALUE nativo, e recriar o tipo do zero num
    # downgrade seria destrutivo demais (perderia qualquer atividade que
    # ja use esse valor). O valor fica no tipo mesmo apos o downgrade.
    for enum_name in ("etapa_processo_enum", "etapa_reuniao_enum", "resultado_reuniao_enum"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
